### ISSUE TITLE
Crash updating master node taints with new pki assets

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/keto-k8#21]
```
Apr 26 08:45:22 ip-172-31-25-28.eu-west-2.compute.internal systemd[1]: kmm.service: Failed with result 'exit-code'.
Apr 26 08:46:37 ip-172-31-25-28.eu-west-2.compute.internal systemd[1]: Starting Kubernetes Multi-master...
Apr 26 08:46:37 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:37Z" level=info msg="Cloud Provider Initialized ["aws"]"
Apr 26 08:46:37 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:37Z" level=info msg="Getting "kmm-asset-key" key value..."
Apr 26 08:46:37 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:37Z" level=info msg="Assets not present in etcd...
Apr 26 08:46:37 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: "
Apr 26 08:46:37 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:37Z" level=info msg="Lock obtained..."
Apr 26 08:46:37 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:37Z" level=info msg="Obtained lock, creating assets..."
Apr 26 08:46:37 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:37Z" level=info msg="Using host:"keto-lewistest-elb-1sn476q2xs5gr-2021831835.eu-west-2.elb.amazonaws.com""
Apr 26 08:46:37 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:37Z" level=info msg="Running:kubeadm alpha phase certs selfsign --cert-altnames keto-lewistest-elb-1sn476q2xs5gr-2021831835.eu-west-2.elb.amazonaws.com"
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:39Z" level=info msg="Output:
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [certificates] Using the existing CA certificate and key.
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [certificates] Generated API server certificate and key.
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [certificates] API Server serving cert is signed for DNS names [ip-172-31-25-28.eu-west-2.compute.internal kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local ke
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [certificates] Generated API server kubelet client certificate and key.
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [certificates] Generated service account token signing key and public key.
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [certificates] Generated front-proxy CA certificate and key.
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [certificates] Generated front-proxy client certificate and key.
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: "
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:39Z" level=info msg="Loading assets off disk..."
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:39Z" level=info msg="Running:kubeadm alpha phase kubeconfig client-certs --client-name kubernetes-admin --server https://keto-lewistest-elb-1sn476q2xs5gr-2021831835.eu-west-2.e
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:39Z" level=info msg="Saving:"/etc/kubernetes/admin.conf""
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:39Z" level=info msg="Running:kubeadm alpha phase kubeconfig client-certs --client-name system:node: --server https://keto-lewistest-elb-1sn476q2xs5gr-2021831835.eu-west-2.elb.a
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:39Z" level=info msg="Saving:"/etc/kubernetes/kubelet.conf""
Apr 26 08:46:39 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:39Z" level=info msg="Running:kubeadm alpha phase kubeconfig client-certs --client-name system:kube-controller-manager --server https://keto-lewistest-elb-1sn476q2xs5gr-20218318
Apr 26 08:46:40 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:40Z" level=info msg="Saving:"/etc/kubernetes/controller-manager.conf""
Apr 26 08:46:40 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:40Z" level=info msg="Running:kubeadm alpha phase kubeconfig client-certs --client-name system:kube-scheduler --server https://keto-lewistest-elb-1sn476q2xs5gr-2021831835.eu-wes
Apr 26 08:46:40 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:40Z" level=info msg="Saving:"/etc/kubernetes/scheduler.conf""
Apr 26 08:46:40 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [apiclient] Created API client, waiting for the control plane to become ready
Apr 26 08:46:41 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [apiclient] All control plane components are healthy after 0.535762 seconds
Apr 26 08:46:41 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [apiclient] Waiting for at least one node to register
Apr 26 08:46:41 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: [apiclient] First node has registered after 0.506556 seconds
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:42Z" level=info msg="Releasing lock..."
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: time="2017-04-26T08:46:42Z" level=info msg="Released lock"
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: panic: assignment to entry in nil map
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: goroutine 1 [running]:
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: github.com/UKHomeOffice/keto-k8/vendor/k8s.io/kubernetes/cmd/kubeadm/app/phases/apiconfig.attemptToUpdateMasterRoleLabelsAndTaints(0xc42096a820, 0x4d, 0x1cd7d20)
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]:         /Users/lewis/go/src/github.com/UKHomeOffice/keto-k8/vendor/k8s.io/kubernetes/cmd/kubeadm/app/phases/apiconfig/setupmaster.go:55 +0x136
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: github.com/UKHomeOffice/keto-k8/vendor/k8s.io/kubernetes/cmd/kubeadm/app/phases/apiconfig.UpdateMasterRoleLabelsAndTaints(0xc42096a820, 0x1a, 0xc42096a820)
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]:         /Users/lewis/go/src/github.com/UKHomeOffice/keto-k8/vendor/k8s.io/kubernetes/cmd/kubeadm/app/phases/apiconfig/setupmaster.go:84 +0x2f
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: github.com/UKHomeOffice/keto-k8/pkg/kubeadm.Addons(0x7ffe76dc0e9a, 0x16, 0x7ffe76dc0da3, 0x1e, 0x7ffe76dc0dd5, 0x22, 0x7ffe76dc0e0a, 0x22, 0x0, 0x0, ...)
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]:         /Users/lewis/go/src/github.com/UKHomeOffice/keto-k8/pkg/kubeadm/addons.go:24 +0xd3
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: github.com/UKHomeOffice/keto-k8/pkg/kmm.bootstrapOnce(0x7ffe76dc0e9a, 0x16, 0x7ffe76dc0da3, 0x1e, 0x7ffe76dc0dd5, 0x22, 0x7ffe76dc0e0a, 0x22, 0x0, 0x0, ...)
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]:         /Users/lewis/go/src/github.com/UKHomeOffice/keto-k8/pkg/kmm/kmm.go:156 +0x213
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: github.com/UKHomeOffice/keto-k8/pkg/kmm.GetAssets(0x7ffe76dc0e9a, 0x16, 0x7ffe76dc0da3, 0x1e, 0x7ffe76dc0dd5, 0x22, 0x7ffe76dc0e0a, 0x22, 0x0, 0x0, ...)
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]:         /Users/lewis/go/src/github.com/UKHomeOffice/keto-k8/pkg/kmm/kmm.go:76 +0x4ba
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: github.com/UKHomeOffice/keto-k8/pkg/kmm/cmd.glob..func4(0x3030fe0, 0xc4201f4aa0, 0x0, 0xa)
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]:         /Users/lewis/go/src/github.com/UKHomeOffice/keto-k8/pkg/kmm/cmd/kmm.go:27 +0x11b
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra.(*Command).execute(0x3030fe0, 0xc420060010, 0xa, 0xa, 0x3030fe0, 0xc420060010)
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]:         /Users/lewis/go/src/github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra/command.go:648 +0x231
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3030fe0, 0x0, 0x1bbf075, 0x207e47f)
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]:         /Users/lewis/go/src/github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra/command.go:734 +0x339
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra.(*Command).Execute(0x3030fe0, 0xc420603f68, 0x1bbf1f4)
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]:         /Users/lewis/go/src/github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra/command.go:693 +0x2b
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: github.com/UKHomeOffice/keto-k8/pkg/kmm/cmd.Execute()
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]:         /Users/lewis/go/src/github.com/UKHomeOffice/keto-k8/pkg/kmm/cmd/kmm.go:38 +0x2d
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]: main.main()
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal docker[8624]:         /Users/lewis/go/src/github.com/UKHomeOffice/keto-k8/cmd/kmm/kmm.go:25 +0x20
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal systemd[1]: kmm.service: Control process exited, code=exited status=2
Apr 26 08:46:42 ip-172-31-25-28.eu-west-2.compute.internal systemd[1]: Failed to start Kubernetes Multi-master.
```

**Comment by lewismarshall** [comment]
This has been fixed - the kubeadm code now handles re-applying taints etc...
