### ISSUE TITLE
keto-k8 fails to start on compute nodes due to runtime error

### ISSUE THREAD

**Issue by KashifSaadat** [UKHomeOffice/keto-k8#41]
The keto-k8 service fails to start when building a compute node, with a runtime error: "invalid memory address of nil pointer dereference"

**Service Logs:**
```
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal systemd[1]: keto-k8.service: Service hold-off time over, scheduling restart.
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal systemd[1]: Stopped keto-k8 (compute).
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal systemd[1]: Starting keto-k8 (compute)...
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x1903a0c]
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]: goroutine 1 [running]:
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]: github.com/UKHomeOffice/keto-k8/pkg/kmm.SetupCompute(0x7ffcd6abcf26, 0x3, 0x3, 0xc4203439a0)
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]:         /go/src/github.com/UKHomeOffice/keto-k8/pkg/kmm/kmm.go:63 +0x6c
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]: github.com/UKHomeOffice/keto-k8/pkg/kmm/cmd.setupCompute(0x30f10a0)
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]:         /go/src/github.com/UKHomeOffice/keto-k8/pkg/kmm/cmd/compute.go:20 +0x73
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]: github.com/UKHomeOffice/keto-k8/pkg/kmm/cmd.glob..func3(0x30f10a0, 0xc4201c3240, 0x0, 0x1)
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]:         /go/src/github.com/UKHomeOffice/keto-k8/pkg/kmm/cmd/compute.go:15 +0x2b
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]: github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra.(*Command).execute(0x30f10a0, 0xc4201c3220, 0x1, 0x1, 0x30
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]:         /go/src/github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra/command.go:648 +0x231
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]: github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x30f1520, 0x0, 0x0, 0x1bda179)
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]:         /go/src/github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra/command.go:734 +0x339
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]: github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra.(*Command).Execute(0x30f1520, 0xc4201c3150, 0xc420583f68)
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]:         /go/src/github.com/UKHomeOffice/keto-k8/vendor/github.com/spf13/cobra/command.go:693 +0x2b
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]: github.com/UKHomeOffice/keto-k8/pkg/kmm/cmd.Execute()
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]:         /go/src/github.com/UKHomeOffice/keto-k8/pkg/kmm/cmd/kmm.go:34 +0x2d
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]: main.main()
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal docker[1275]:         /go/src/github.com/UKHomeOffice/keto-k8/cmd/kmm/kmm.go:26 +0x22
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal systemd[1]: keto-k8.service: Control process exited, code=exited status=2
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal systemd[1]: Failed to start keto-k8 (compute).
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal systemd[1]: keto-k8.service: Unit entered failed state.
Jun 28 09:15:02 ip-172-30-1-144.eu-west-1.compute.internal systemd[1]: keto-k8.service: Failed with result 'exit-code'.
```

**Comment by lewismarshall** [comment]
Fixed by #43
